# Generated by Django 2.1 on 2019-12-22 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cycles',
        ),
        migrations.AddField(
            model_name='cell',
            name='artifact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.Artifact'),
        ),
        migrations.AddField(
            model_name='game',
            name='cycle_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='game_status',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='is_cycle_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='termination_condition',
            field=models.CharField(default='finish', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='termination_value',
            field=models.IntegerField(default=0),
        ),
    ]
