# Generated by Django 2.1 on 2019-12-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20191222_0520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='cuurent_round',
            new_name='current_round',
        ),
    ]
