# Generated by Django 2.1 on 2019-12-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20191222_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ready_player_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
