# Generated by Django 2.1 on 2019-12-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_ready_player_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='player_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
