# Generated by Django 2.1 on 2019-12-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20191222_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='player_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
