# Generated by Django 2.1 on 2019-12-22 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20191222_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.ActionName'),
        ),
    ]
