# Generated by Django 2.1 on 2019-12-22 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20191222_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.Player'),
        ),
    ]
