# Generated by Django 2.1 on 2019-12-22 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.Artifact'),
        ),
    ]
