# Generated by Django 2.1 on 2019-12-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_player_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='next_available_move',
            field=models.CharField(default='roll', max_length=20),
        ),
    ]
