# Generated by Django 2.1 on 2019-12-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_player_next_available_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='artifact_count',
            field=models.IntegerField(default=0),
        ),
    ]
