# Generated by Django 2.1 on 2019-12-23 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20191222_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.Player'),
        ),
    ]
