# Generated by Django 2.1 on 2019-12-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_artifact_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='player_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_ended',
            field=models.BooleanField(default=False),
        ),
    ]
