# Generated by Django 2.1 on 2019-12-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20191222_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='player_id',
            field=models.IntegerField(default=0),
        ),
    ]
