# Generated by Django 2.1 on 2019-12-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20191222_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='player_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
