# Generated by Django 2.1 on 2019-12-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20191222_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='player_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.Action'),
        ),
    ]
